### ISSUE TITLE
Animation system

### ISSUE THREAD

**Issue by kvark** [three-rs/three#10]
Having a decent animation capability is essential to any dynamic visualization. It's also needed for basic orbital camera controls, which are used in quite a few Three.js demos.

Main difficulty comes from the fact that some data is stored both locally and remotely, e.g. local transformations and materials.

cc @ozkriff

**Comment by kvark** [comment]
One (rather simple) idea is to have all the animation to work on `Pointer<Node>` of the objects, thus only modifying the remote state. Each object would then have a flag that tells if the local state is de-synchronized from the remote one, and access to the local state would trigger an `error!` if it's not synced. I've just [added](https://github.com/kvark/three-rs/commit/5082a137405c1dafda985ebabe2418f6bb95af01#diff-1f0541119ecba5576327a7349c7d9aefR104) the `sync()` methods to re-synchronize local data with the remote one for all objects.

**Comment by kvark** [comment]
Also see Three's animation system here:
https://threejs.org/docs/#manual/introduction/Animation-system

Skinning and mesh morphing are specific cases that need their own bugs.

**Comment by nchashch** [comment]
I was thinking about animation mechanism design for amethyst lately, maybe it would be useful for three-rs too. See [this](https://github.com/amethyst/amethyst/issues/214#issuecomment-325155960) comment.

**Comment by alteous** [comment]
Is there anything left to discuss here? #103 provides a basic animation framework. The remaining features are scheduled in #149.

**Comment by vitvakatu** [comment]
I think we can close this now, any (possible) changes to current implementation should be discussed elsewhere.
