### ISSUE TITLE
[RFC] Input ergonomics (draft)

### ISSUE THREAD

**Issue by vitvakatu** [three-rs/three#114]
Input ergonomics is one of our problems atm:
```rust
!three::KEY_ESCAPE.is_hit(&win.input)
```
doesn't seem logical (why we pass input to button?)
## Brief overview of the current implementation
Three main concepts: `Button`, `KeyAxis`, `Input`.
- `Button` - enum of either keyboard or mouse button.
- `KeyAxis` - struct of two keyboard buttons.
- `Input` struct that contains current input state.
### Problems
- `button.is_hit(input)` seems weird, more traditional way is `input.is_hit(button)`
- No ability to handle input from non-keyboard axes
- Provided methods aren't ideal (can you give me an example of using `hit_count`?)
- `Timer` can be more powerful.

# Proposals
1. Replace `KeyAxis` with more flexible `Axis` type (enum?) to give user an ability to handle raw input from any devices.
2. Change API: move methods of `KeyAxis` and `Button` to the `Input`
3. Indexing API for proxy-objects provided by `Input`. E.g. `if win.input.down[KEY_SPACE]` or `if win.input.hits[KEY_ESCAPE] == 0`.
4. Give user an ability to reset current input state (make `reset` method public) and an ability to disable reset on every `render`.
5. It would be great if we can give our `Timer` an ability to update his state without involving `Input` (like timers in others game engines)

Be careful, I'm not saying that we should implement all proposals listed here.

**UPD**
As far as I can see all proposals were accepted without any concerns.
Here is the plan for implementation:
1. Replace `KeyAxis` with `enum Axis { Key, Custom }`
2. Provide proxy-objects for `Input` to replace existing methods: 
* `down[Button]` 
* `up[Button]`
* `hits[Button]`
* `axis_hits[Axis]`
* `axis_time[Axis]`
3. Provide method `Window::input_reset(bool)` to enable/disable input reseting
4. Expose `Input::reset` method

There were other proposals - get rid of event loop and improve `Timer`, but it's for different PRs.

**Comment by kvark** [comment]
Sounds good, the proposed ideas are promising :)
Please note that the original approach to have `button.is_hit(input)` is based on the idea that we can have more accessors that `Input` may not even be aware of (read: extensible?). However, I don't think this worked out nicely, so I think we can turn this around, like proposed.

**Comment by alteous** [comment]
Input event polling is currently performed during `Window::update`. Would it be a bad idea to move the polling outside of window? I understand there are some dependencies between `Window`, `Input`, and `Renderer`. We could perhaps use a channel to relay the information.

**Comment by vitvakatu** [comment]
@alteous where do we want to see polling?

**Comment by alteous** [comment]
The motivation was to have event handling independent of rendering so that events can be polled on another thread and hence would not be blocked by nor dependent on the graphics pipeline.

```rust
extern crate three;

fn main() {
    let shaders_path = concat!(env!("CARGO_MANIFEST_DIR"), "/data/shaders");
    let mut win = three::Window::builder("Example", shaders_path).build();
    
    let cam = win.factory.perspective_camera(60.0, 1.0 .. 10.0);
    let mut controls = three::controls::Orbit::builder(
        &cam,
        [0.0, 2.0, -5.0],
        [0.0, 0.0, 0.0]
    ).build();

    while win.update() {
        let input = win.input.poll();
        if three::KEY_ESCAPE.is_hit(&input) {
            break;
        }
        controls.update(&input);
        win.render(&cam);
    }
}
```

**Comment by alteous** [comment]
It might be difficult to achieve but I think returning a tuple `(Window, Renderer, Factory, EventLoop)` might be better than `Window`. I'm only speculating though.

**Comment by alteous** [comment]
I've also been thinking about taking a callback instead of an explicit loop. This would be especially useful for emscripten since we have to set a 'main loop' callback with `emscripten_set_main_loop`.

The code might look like this.

```rust
extern crate three;

fn main() {
    let shaders_path = concat!(env!("CARGO_MANIFEST_DIR"), "/data/shaders");
    let mut win = three::Window::builder("Example", shaders_path).build();
    
    let cam = win.factory.perspective_camera(60.0, 1.0 .. 10.0);
    let mut controls = three::controls::Orbit::builder(
        &cam,
        [0.0, 2.0, -5.0],
        [0.0, 0.0, 0.0]
    ).build();

    win.main_loop(|input, renderer, factory| {
        controls.update(&input);
        win.render(&cam, &input);
    });
}
```

**Comment by vitvakatu** [comment]
> Actually (to quote myself), maybe it would be better if Renderer::render was somehow non-blocking instead.

Not sure it's possible, afaik we can't render neither from another thread nor async.

I'm not the fan of callbacks, but I'm not against, we need to thought about it.

**Comment by vitvakatu** [comment]
@kvark @alteous I've updated first message, so now we have rough plan of implementation.
Express your opinion and I'll go to implementation ASAP.

**Comment by alteous** [comment]
@vitvakatu Stupid question: What does input resetting do?

**Comment by vitvakatu** [comment]
@alteous you can separate input handling and rendering, may be useful for some games
