### ISSUE TITLE
Massive `sync`s

### ISSUE THREAD

**Issue by vitvakatu** [three-rs/three#134]
It's common situation while programming game when you need to update information about multiple objects. For example, update positions of every enemy and cache in `Enemy` type for future using.

But the `Object::sync` is too slow because it updates the whole scene graph every time it's called.
So I present rough idea how to handle these situations:
```rust
// `Enemy` must implement `AsRef<Object>`
let mut enemies: Vec<Enemy> = create_enemies();
//...
// somewhere in main loop
// `with_sync` will update scene graph once
let sync = window.scene.with_sync();
// First argument is iterator, second one is working closure.
sync.update(&mut enemies, |_, node_info| { println!("Enemy at: {}", node_info.world_transform.position); });
sync.update(&mut enemies, |mut enemy, node_info| { enemy.position = node_info.world_transform.position; });
```

There are a lot of questions about implementation (for example, how to allow to pass any iterator in), but the core idea should be clear.

What do you think?

**UPD: code example updated after short discussion on gitter**

**Comment by alteous** [comment]
As discussed on Gitter, we could avoid the second closure by requiring `Enemy: AsRef<Object>` à la your example.
