### ISSUE TITLE
Noisy build messages

### ISSUE THREAD

**Issue by alteous** [three-rs/three#137]
Caused by warnings of changing include/exclude rules. See this [Travis log](https://travis-ci.org/three-rs/three/jobs/292852306#L484-L522) for example.

**Comment by vitvakatu** [comment]
Should be very easy to fix, see https://github.com/rust-lang/cargo/issues/4268

**Comment by alteous** [comment]
Thanks. All that's required is to change `include = ["data"]` to `include = ["data/shaders/*.glsl", "data/fonts/*.ttf"]`.

**Comment by alteous** [comment]
`include = ["./data/"]` is better.
