### ISSUE TITLE
Make Timer independent

### ISSUE THREAD

**Issue by vitvakatu** [three-rs/three#166]
It's a shame that you can neither create, nor use `Timer` without `Input`.

**Comment by kvark** [comment]
Dunno if it's really a shame though. Time is sort of an input, just not coming from the user.
Do you have an example were you need to create timers somewhere deep the code stack?

**Comment by vitvakatu** [comment]
For example, [here](https://github.com/vitvakatu/asteroids/blob/cdebadb26eb081e0c37deea42ac850c287b99dfb/src/bullet.rs#L43). The only reason to pass `Input` to the function is timer creation. It makes no sense, why should I provide input information while creating objects?

**Comment by alteous** [comment]
There doesn't seem to be any analogous timer feature in three.js, so I assume `struct Timer` is something unique to us? If so, it seems like a rather trivial wrapper around `std::time::Duration`. Not a criticism, just an observation.
