### ISSUE TITLE
Planar quad has winding issues

### ISSUE THREAD

**Issue by kvark** [three-rs/three#191]
One of the triangles is culled for the winding order.
cc @eddyb

**Comment by vitvakatu** [comment]
Can't confirm in `lights` example. (And anywhere else)

**Comment by kvark** [comment]
@vitvakatu same for me. Going to close this for now until we figure out what exactly is wrong.
FWIW, the plane largely just gets data from `genmesh`, which has a winding order test to validate it for all primitives.
