### ISSUE TITLE
Fix build script

### ISSUE THREAD

**Issue by kvark** [three-rs/three#194]
Our current `build.rs` uses `includedir_codegen` with a wildcard for `rerun-if-changed`, which is not supported (also see https://github.com/tilpner/includedir/issues/3). Instead, we could manually iterate the shader files like WR does: https://github.com/servo/webrender/blob/master/webrender/build.rs
cc @eddyb

**Comment by tilpner** [comment]
Upgrading to includedir 0.3.0 should fix this, thanks for reporting. :)

**Comment by kvark** [comment]
Fixed by #193
