### ISSUE TITLE
No method named 'load_gltf' error when running examples

### ISSUE THREAD

**Issue by mriede** [three-rs/three#198]
Hey

I'm having trouble getting the GLTF examples to compile. Cargo aborts the build with 
```no method named `load_gltf` found for type `three::Factory` in the current scope```

Can't find the method in the documentation for this crate either, do you have an idea?
Awesome framework, by the way!

Best regards

**Comment by kvark** [comment]
@mriede hello!

How are you trying to run the examples, exactly?

Here is what I get:
>[kvark@carbon three-rs]$ cargo run --example gltf-pbr-shader
error: target `gltf-pbr-shader` requires the features: `gltf-loader`
Consider enabling them by passing e.g. `--features="gltf-loader"`
>[kvark@carbon three-rs]$ cargo run --example gltf-pbr-shader --features gltf-loader
> ... cargo building stuff ...
>     Finished dev [unoptimized + debuginfo] target(s) in 208.70 secs
     Running `target/debug/examples/gltf-pbr-shader`
Loading "/home/kvark/Code/three-rs/test_data/Lantern/Lantern.gltf" (this may take a while)

(this is where the app is interactable, and works)

**Comment by mriede** [comment]
I pasted one of the examples into a new project, the actual examples from your repository compile without any problems. I'm just stuck on how to integrate this library into a new crate. This is my Cargo.toml:

```
[package]
name = "..."
version = "0.1.0"
authors = []

[features]
default = ["opengl"]
gltf-loader = ["gltf", "gltf-importer", "gltf-utils"]
opengl = ["gfx_device_gl", "gfx_window_glutin", "glutin"]

[dependencies]
three = "0.3.1"

# GLTF
gltf = { features = ["names"], optional = true, version = "0.9.3" }
gltf-importer = { features = ["names"], optional = true, version = "0.9.3" }
gltf-utils = { features = ["names"], optional = true, version = "0.9.3" }

# OpenGL
gfx_device_gl = { version = "0.15", optional = true }
gfx_window_glutin = { version = "0.20", optional = true }
glutin = { version = "0.12", optional = true }
```

**Comment by vitvakatu** [comment]
You don't need to set all those deps in your `Cargo.toml`. All you need is
```toml
[dependencies]
three = { version = "0.3.1", features = ["gltf-loader"] }
```

**Comment by mriede** [comment]
Thanks, that worked perfectly. Sorry for any inconvenience!
