### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rukai** [three-rs/three#208]
I dont know what the process is normally for this crate, but I would like to see a 0.4 release so I can use https://github.com/three-rs/three/commit/5b2a79b5cb9a9b528f4d2bd459a4bc4322f1107f and https://github.com/three-rs/three/commit/694572af2f4c67464f42cb6f875e86c06fec7fb5

**Comment by kvark** [comment]
@rukai we'll need to merge #206 and update all the dependencies for that, e.g. `glutin`.

**Comment by rukai** [comment]
I'm curious what the future of this project is.
Its currently built on top of pre-hal gfx, is it planned to upgrade to gfx-hal someday?

**Comment by kvark** [comment]
It's either going to be moving to gfx-hal, or to wgpu-rs, which is more likely and less resource consuming.

**Comment by rukai** [comment]
Cool thanks, I'll have a PR up in a sec to update three-rs's existing dependencies.

**Comment by kvark** [comment]
This has happened :tada: !
https://crates.io/crates/three/0.4.0
also see #219
