### ISSUE TITLE
Question: What vector type should I use?

### ISSUE THREAD

**Issue by njlr** [three-rs/three#223]
A bit new to Rust so please forgive me if I have gotten something wrong!

Looking at the examples, I think I should be using `mint::Vector2<f32>` to represent points in 2D space. However, there do not seem to be operators implemented for those types. 

For example, this won't work: 

```
position: self.position + self.velocity
```

Should I be using these vector types for my game logic?

If not, what is the recommended way?

**Comment by kvark** [comment]
`mint` is a library for interop only, it doesn't provide any computation. The idea is that users choose whatever they are comfortable with, i.e. cgmath/nalgebra/euclid, and just pass those types to us, and they get auto-converted into `mint`. Check out how examples do it.

**Comment by njlr** [comment]
`cgmath::Vector2<f32>` does what I need.

Thanks!
