### ISSUE TITLE
Is window mandatory? can this library be used headlessly?

### ISSUE THREAD

**Issue by gre** [three-rs/three#238]
I'm looking for a library to be able to do some 2D plotting (with an axidraw) and essentially want to make a 3D Scene graph that I project into wireframe of the 3D objects. I thought this library is high level enough to work on doing that, however I imagine I would have to rewrite some part? Make my own renderer?

When tackling some code, it appears to me that Renderer implicitly depends on the context of a Window and this library have a strong dependency on GL, so maybe it's not a so good candidate or do you think it could work?🤔  Feel free to close this issue if you think this is out of scope.

Thanks

**Comment by kvark** [comment]
At this point, you probably don't want to start a new project on three-rs. It needs to be ported to wgpu-rs in order to live.

**Comment by gre** [comment]
Ok thanks for feedback
