### ISSUE TITLE
Shader code vendoring

### ISSUE THREAD

**Issue by kvark** [three-rs/three#28]
Current approach requires the user to copy the shaders folder, which is unfortunate. A proper alternative might be to include the shaders in the code (with `include_bin!`), plus allow overrides from the file system for fast iteration.

cc @alexander-irbis

**Comment by alexander-irbis** [comment]
If you look back at three.js, the basic things there are already included in the package and the user begins to add something of his own, only when the basic capabilities begin to be missed. If you go further - three.js generates the shaders in accordance with the settings of renderer (but I don't know how useful this property is). On this side, the user who will not go into the mechanics of shaders, he just need to keep them up to date.

On the other hand, fast reload without restart a program is really sweet feature at the drafting stage. It will be very useful for advanced users. But again user need to remember about the need to merge changes from upstream if he go to change standard shaders.

Probably it would still be nice to separate standard shaders from custom ones, to enable and use standard shaders, and to develop your own.

**Comment by kvark** [comment]
How about the following plan:
  - the renderer has all the shader code included from the source templates, an it potentially modifies it based on the user settings before linking
  - user may invoke a dump of the shaders to a specified folder (from the code, supposedly)
  - user may request a hot reload of the shaders from a specified folder. The engine may detect the change and re-load only changed shaders.

**Comment by vitvakatu** [comment]
> user may invoke a dump of the shaders to a specified folder (from the code, supposedly)

How the user should use this opportunity? Create side application just to dump standard shaders (and change them then)? Or maybe dump and change them from code at runtime (sounds like disaster).

**Comment by kvark** [comment]
@vitvakatu at runtime. It's not a disaster since this is not supposed to be used in production.

**Comment by alexander-irbis** [comment]
I think the problem should be divided into two parts.

The developers of three-rs need to work with the shaders of the library. But they know where to get the shaders and what to do with them.

The user needs to develop his own shaders, for example, post-effects and may want to use the same mechanics to fast reload them.

These parts do not intersect directly with each other, but complement each other.

But there may be another scenario: user use third party libs, which will generate the necessary shaders and resources.

As a result, we get a loader with scoped updates from several places.

**Comment by alexander-irbis** [comment]
And then, with sophisticated generators, possibility to dump current state of all generated stuff to explore and may be fix a resulting shaders' code will be very useful in itself.

**Comment by alteous** [comment]
Perhaps some 'shader state' could be managed by `Factory`. The default state would be the default shaders, baked into the program. At runtime, the user would be able to call a function `Factory::set_shader(&must self, /* data */) -> Result<(), CompilationError>` to override the defaults.

**Comment by kvark** [comment]
Fixed by #124
