### ISSUE TITLE
Material definition

### ISSUE THREAD

**Issue by kvark** [three-rs/three#31]
Current approach with materials being an `enum` is not quite scalable given that the user will be forced to set all sorts of parameters they don't care about. There are several approaches here:
  
  1. Have helper constructors with fewer parameters
  2. Have it a structure with `Default` implemented for it and multiple features behind options/enums as fields.
  3. Have distinct material types, at least on the user side, all implementing `Default`.

When designing this, the biggest question is how to properly support custom materials.

**Comment by alteous** [comment]
### Proposed ideas

Both ideas revolve around making `Material` into a `struct`.

#### Non-opaque

```rust
pub enum Pipeline {
    Basic,
    Lambert,
    Phong,
    Pbr
    Sprite,
    // etc.
}

pub struct Material {
    pub pipeline: Pipeline,
    pub color: Color,
    pub map: Option<Texture<[f32; 4]>>,
    pub wireframe: bool,
    pub flat: bool,
    pub glossiness: f32.

    pub base_color_factor: [f32; 4],
    pub metallic_roughness: [f32; 2],
    pub occlusion_strength: f32,
    pub emissive_factor: [f32; 3],
    pub normal_scale: f32,
    pub base_color_map: Option<Texture<[f32; 4]>>,
    pub normal_map: Option<Texture<[f32; 4]>>,
    pub emissive_map: Option<Texture<[f32; 4]>>,
    pub metallic_roughness_map: Option<Texture<[f32; 4]>>,
    pub occlusion_map: Option<Texture<[f32; 4]>>,
}
```

#### Opaque

```rust
/* private */ enum Pipeline {
    Basic,
    Lambert,
    Phong,
    Pbr
    Sprite,
    // etc.
}

pub struct Material {
    pipeline: Pipeline,
    bits: u32,
    /// Corresponds to `color` in the basic pipeline and `base_color_factor` in the PBR pipeline etc.
    color: Color,
    params: [f32; 12],
    textures: [Option<Texture<[f32; 4]>>; 6],
}

impl Material {
    pub fn basic(color: Color, map: Option<Texture<[f32; 4]>, wireframe: bool) {
        Material {
            pipeline: Basic,
            color,
            textures: [map, None, None, None, None, None],
            bits: WIREFRAME_BIT,
        }
    }
}
```

**Comment by vitvakatu** [comment]
I don't think we need feature flags here.

**Comment by kvark** [comment]
Thanks for the detailed description!

I'd like to explore the potential approach of hiding material types behind some sort of abstraction (not necessarily an opaque one), as described in https://github.com/three-rs/three/pull/105#discussion_r138632264

We probably still need to specify what sort of geometry we want to run on, but otherwise - the actual lighting model could be derived from the properties we specify (think - node graph for materials).

```rust
let material = Material {
    mesh: mat::Mesh::Geometry, // could be Point, Line, Sprite alternatively
    color: mat::Color { value: Color, map: None }, // non optional
    normal: Some(mat::Normal { scale: f32, map: my_texture }), // figures that at least Lambert diffuse model is needed
    specular: Some(mat::Specularity { glossiness: 20.0, map: None }), // figures that at least Phong specular is needed
    .. default() // has all the rest of PBR and whatnot set to `None`
};
```

**Comment by alteous** [comment]
Could we close this now? The new material API works nicely, so it seems all is left to discuss is custom materials.

**Comment by vitvakatu** [comment]
We've implemented this, closing now.
