### ISSUE TITLE
Auto-instancing

### ISSUE THREAD

**Issue by kvark** [three-rs/three#37]
We have just a handful of different PSOs, and we can have lots of draw calls. Given that we populate all the local data anyway, we could build it with instanced buffers and issue fewer calls.
Related - #36

**Comment by alteous** [comment]
When might auto-instancing begin? We would have to define precisely what 'lots of draw calls' means.

Perhaps the user could provide a hint to the crate that specifies when multiples of the same renderable might benefit from instancing.

**Comment by vitvakatu** [comment]
@alteous see `mesh_instance` function

**Comment by kvark** [comment]
> We would have to define precisely what 'lots of draw calls' means.

We have a clear test case - take the `group` demo and increase the depth of cubes to 6 or 7, and you'll see ;) Of course, it's rather limited, but a good place to start optimizing for.

> When might auto-instancing begin?

As @vitvakatu noted, `mesh_instance` should be enough input from the user already. We need to batch the draw calls of the same (material, mesh) pair by recording their local parameters into entries in instanced vertex buffers.
