### ISSUE TITLE
Node children lifetime

### ISSUE THREAD

**Issue by kvark** [three-rs/three#44]
It appears to be counter-obvious that we have `parent.add(&child)` yet it's not parent holding the child alive but the other way around. In some cases, this goes in the way of encapsulation: e.g. when we load a number of different things from a file, we may want to return a single group that everything is attached to, yet today if you do this - all the children will get removed for losing the references.

There does not appear to be an easy way to address this, on the technical level. The implementation largely prefers storing the parents only and working with them. Ideas:
  1. Keep the children locally by groups and scenes. Problem: hard to synchronize with those children changing parents.
  2. Have `children: Vec<Pointer<Node>>>` alongside `parent: WeakPointer<Node>` in the nodes. Problem: traverse performance, given that accessing children array is expensive, and accessing the parent requires conversion to a strong pointer...
  3. Leave the implementation as is, but change the API to `child.attach(&parent)` to make the relationship clear.

**Comment by vitvakatu** [comment]
I prefer the last solution.

**Comment by alteous** [comment]
I'm not a fan of 2. I didn't quite follow 1, could you explain with a code example?

**Comment by vitvakatu** [comment]
@alteous first one is about storing `Vec<Node>` inside `Group`s, not inside `Hub` (if I understood correctly).

**Comment by alteous** [comment]
@vitvakatu If that's the case then I'm not a fan of 1 neither.

What's quite nice is one can always store the leaf nodes with the parent and use `three_object_wrapper!` to manage them as one entity.

```rust
struct ComplexModel {
    /// Parent of all meshes.
    object: Group,
    /// The meshes (leaf nodes) of the object.
    meshes: Vec<Mesh>,
}
```

**Comment by alteous** [comment]
During #86 I thought about replacing `three_object_wrapper!` with a procedural macro, but later dismissed the idea since it didn't have many tangible benefits. Do you think a `proc_macro` could be used to remedy this issue?

**Comment by alteous** [comment]
The idea was something like
```rust
#[derive(Object)]
struct ComplexModel {
    meshes: Vec<Mesh>,
}
```

**Comment by vitvakatu** [comment]
Pushed high priority because we need to make decision ASAP.

**Comment by alteous** [comment]
>  we need to make decision ASAP.

We do?!

**Comment by vitvakatu** [comment]
@alteous this is serious architectural issue, so we need to solve it to move forward. I'm for `attach` variant, as I said beforehand.

**Comment by alteous** [comment]
I actually like the API the way it is currently. It might be initially counter-intuitive but one only needs to be told once. `child.attach(&parent)` mimics what the implementation does but it doesn't make the intention any clearer.

For clarity's sake, consider these code snippets:

#### Proposed
```rust
let group = factory.group();
let mesh = factory.mesh(geometry, material);
mesh.attach(&group);
scene.attach(&group);
```

#### Current
```rust
let group = factory.group();
let mesh = factory.mesh(geometry, material);
group.add(&mesh);
scene.add(&group);
```

**Comment by vitvakatu** [comment]
What about
```rust
let group = factory.group();
let mesh = win.factory.mesh(geometry, material);
mesh.attach_to(&group);
group.attach_to(&win.scene)
```

**Comment by alteous** [comment]
I've had to make two amendments to https://github.com/three-rs/three/issues/44#issuecomment-330079993 because the code was incorrect!

**Comment by vitvakatu** [comment]
Okay, it may seem counter-intuitive to the user at the beginning, but if we can explain it with our docs - `add` is good choice (smaller and more memorable)

**Comment by alteous** [comment]
`attach_to` is slightly better than `attach` but I still think `add` is more friendly.

**Comment by alteous** [comment]
I briefly considered having both, to let the user decide, but quickly dismissed the idea.

Can you imagine...?! :smile: 

```rust
let group = factory.group();
let mesh = factory.mesh(geometry, material);
mesh.attach_to(&group);
scene.add(&group);
```

**Comment by vitvakatu** [comment]
We should allow user to create his own syntax rules! 😄

**Comment by alteous** [comment]
It's not the [worst idea I've ever come up with](https://github.com/alteous/gltf-legacy/blob/8a8cb706e52e609672e29a2f8c70379ad0ae8e12/src/v1/extras.rs#L15-L100), at least.

**Comment by vitvakatu** [comment]
Okay, I think we reach consensus, so I'm closing this issue. If someone has different opinion (@kvark or @csherratt or anyone else) - feel free to reopen.

**Comment by kvark** [comment]
@vitvakatu I'm not quite satisfied with the consensus (yet?). We haven't really solved the problem of API not matching what the code does. It will surely screw people over when Three-rs gets more attention.

**Comment by alteous** [comment]
Crazy idea: How about a macro?

```rust
let group = factory.group();
let mesh = factory.mesh(geometry, material);
link!(mesh -> group);
link!(group -> scene);
```

**Comment by vitvakatu** [comment]
In what code it would be expanded?

**Comment by alteous** [comment]
Either of the ideas expressed above. The macro would exist to make the relationship between child and parent clear.

```rust
macro_rules! link {
    ($child:expr -> $parent:expr) => {
        child.attach_to(&parent);
    };
}
```
or equivalently
```rust
macro_rules! link {
    ($child:expr -> $parent:expr) => {
        parent.add(&child);
    };
}
```

**Comment by vitvakatu** [comment]
Then we can just go with `link` or `link_to` (pretty similar to `attach`).

**Comment by alteous** [comment]
```rust
let group = factory.group();
let mesh = factory.mesh(geometry, material);
mesh.link_to(&group);
group.link_to(&scene);
```
If I swap the children with the parents...
```rust
let group = factory.group();
let mesh = factory.mesh(geometry, material);
group.link_to(&mesh);
scene.link_to(&group);
```

**Comment by alteous** [comment]
How about `set_parent`?
```rust
let group = factory.group();
let mesh = factory.mesh(geometry, material);
mesh.set_parent(&group);
group.set_parent(&scene);
```

**Comment by kvark** [comment]
@alteous I like `link_to`, and I think I like `set_parent` even more.
Would it be correct to just have `parent()` as a verb?

**Comment by alteous** [comment]
We could have `parent` as a verb. Is there any chance of a function returning the parent of a node (because then it's name would also be `parent`)?

**Comment by kvark** [comment]
on a second thought, `set_parent` is cleaner and less ambiguous
