### ISSUE TITLE
[Question] Builders API

### ISSUE THREAD

**Issue by vitvakatu** [three-rs/three#57]
At the moment `WindowBuilder` is constructed via `Window::new` method, that isn't common behavior for `new` methods. (see [clippy lint](https://github.com/Manishearth/rust-clippy/wiki#new_ret_no_self))
cc @kvark @shmutalov

**Comment by shmutalov** [comment]
I would like to construct Window with seperate and explicit builder with different name a.k.a `WindowBuilder`

**Comment by vitvakatu** [comment]
@alexander-irbis  suggested `Window::build_new() -> WindowBuilder`

**Comment by vitvakatu** [comment]
@shmutalov suggested `Window::new` method without parameters:
```rust
let w = Window::new()
    .with_caption("title")
    .with_size(800, 600)
    .build();
```

**Comment by alteous** [comment]
I suggest `Window::builder`.

**Comment by vitvakatu** [comment]
I'm going to fix this issue as a part of reorganization coming soon
