### ISSUE TITLE
Input ergonomics

### ISSUE THREAD

**Issue by kvark** [three-rs/three#60]
Current system was rolled in as a (somewhat nice) abstraction. This is not, however, a priority for three-rs.
Seeing `if three::Button::Key(three::Key::Left).is_hit(&win.input) {..}` expressions make me cringe. We should make it nicer without sacrificing the abstraction, e.g.:
```rust
if win.input & three::Key::Left {..}
```

**Comment by vitvakatu** [comment]
It looks interesting. I'll try to implement it now and we'll see how it looks like.

**Comment by kvark** [comment]
Small warning: I recall actually going back and forth with the operator design and for some reason decided to back it off when I was first rolling out the input system.
We need to be careful and pay attention to details here.
👍 for giving it a try!

**Comment by vitvakatu** [comment]
Operators are consuming, so it makes `win.input & key` impossible. `key & win.input` will be possible, however, but we need `Copy` for `Key`

**Comment by vitvakatu** [comment]
Now you can write `three::Key::Left & &win.input` instead of `three::Button::Key(three::Key::Left).is_hit(&win.input)`
