### ISSUE TITLE
Render Buster Drone for Show Time

### ISSUE THREAD

**Issue by alteous** [three-rs/three#85]
See [SketchFab](https://sketchfab.com/models/294e79652f494130ad2ab00a13fdbafd) for a WebGL render of the model. Note the performance of the render is not amazing - at least on my machine.

Would this be a suitable model for showing off the capabilities of the crate?

**Comment by vitvakatu** [comment]
I think it's okay. For your information, I will take part in russian rust gamedev meetup at September 14, it would be cool if we will be ready at the time.

**Comment by alteous** [comment]
I'll do my best. :smile:

**Comment by alteous** [comment]
The size of this model is slightly ridiculous. Is it normal for models to have textures of size 4096x4096?

**Comment by alteous** [comment]
It would be okay if there were only one texture, but there are an equivalent of five 4096x4096 textures! In release mode, loading all the data stalls my PC. :joy:

**Comment by alteous** [comment]
![screenshot_20170913_114625](https://user-images.githubusercontent.com/8549126/30373433-384b446a-9879-11e7-9f33-7c12d8648dda.png)
This is how it looks so far, without animations. I think vertex skinning is required.

**Comment by alteous** [comment]
![screenshot_20170913_114955](https://user-images.githubusercontent.com/8549126/30373575-b1763cbe-9879-11e7-82ce-bc11f8faad33.png)
A bit lighter.

**Comment by alteous** [comment]
Hmm... the glTF exported from SketchFab doesn't include the animations, only this static pose. I'll download the original FBX version and see if it can be converted. If not then, unfortunately, we won't be able to showcase this. :worried:

**Comment by kvark** [comment]
It says the following in the file description:
> C4D17 Rig and Animation File Included

**Comment by alteous** [comment]
@kvark Yes, but it's missing from the glTF export. I'm trying to download the original FBX version but it's taking a crazy amount of time to package up. I'm not sure if the download is making any progress at all...

![screenshot_20170913_155834](https://user-images.githubusercontent.com/8549126/30384522-6f9abea0-989c-11e7-9a4c-44d1a1514e1a.png)

**Comment by kvark** [comment]
@alteous I contacted the author directly (Michael Bitsakis). He is in Greece, so there is a chance we get an answer soon, but don't hold your breath...

**Comment by kvark** [comment]
Good news, we got an answer. Bad news - they don't have the animated version, saying it's not really their model :( So FBX is our best bet.

**Comment by alteous** [comment]
@kvark Thanks for investigating. That's a shame. Hopefully, I'll be able to download the FBX version asap.

@vitvakatu Would you mind trying to download this too?

**Comment by kvark** [comment]
This is what Michael provided:
[BusterDrone.zip](https://github.com/three-rs/three/files/1300762/BusterDrone.zip)

**Comment by alteous** [comment]
@kvark @vitvakatu Great news: I've managed to get BusterDrone in a working state. I had to do some manual editing to include the textures, so it might not look amazing, however, the animations are working and will be ready for the Russian gamedev meetup.

In order to run, you will need to build #103 and pass the following arguments:

`cargo run --release --example gltf-animation -- test_data/BusterDrone/BusterDrone.gltf`

If you have the glTF sample models downloaded, I would recommend trying out BoxAnimated and CesiumMilkTruck too.

**Comment by alteous** [comment]
For future reference, I took the following steps to get the model in a working state:

1. Obtain origin FBX file from https://github.com/three-rs/three/issues/85#issuecomment-329278304.
2. Install the [glTF-Blender-Exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter).
3. Import FBX into Blender and export as glTF 2.0.
4. Resize and vertically flip all the textures using ImageMagick or otherwise.
5. Manually add the `images`, `textures`, and `samplers` properties to the glTF.
6. Manually edit the `materials` properties of the glTF to reference the textures.

**Comment by alteous** [comment]
This should be the result.
![screenshot_20170914_130334](https://user-images.githubusercontent.com/8549126/30430164-422ed1fc-9952-11e7-8956-dd4bd9945941.png)
