### ISSUE TITLE
Access underlaying Glutin window

### ISSUE THREAD

**Issue by moonheart08** [three-rs/three#94]
In some cases it might be useful (highly, even, in the case of conrod) to access the raw glutin window. Maybe a method that returns a pointer to it and the event loop?

**Comment by kvark** [comment]
I don't want to expose `glutin::Window`, since it's GL-only, but I think having a method providing `&winit::Window` is totally doable.

**Comment by moonheart08** [comment]
@kvark That works perfectly as well. I may look into solving my own issue.

**Comment by vitvakatu** [comment]
Shoudn't we provide it behind the feature flag?
